# Generated by Django 3.2 on 2021-06-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='time',
        ),
        migrations.RemoveField(
            model_name='account',
            name='voice',
        ),
        migrations.AddField(
            model_name='account',
            name='auto_friends',
            field=models.BooleanField(default=True, verbose_name='Автоматическое добавление в друзья'),
        ),
        migrations.AddField(
            model_name='account',
            name='base_name',
            field=models.CharField(default='base.bin', max_length=15, verbose_name='База ответов'),
        ),
        migrations.AddField(
            model_name='account',
            name='commands',
            field=models.TextField(default='', verbose_name='Команды (не работает)'),
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.PositiveIntegerField(default=0, verbose_name='id сообщества, у пользователей = 0'),
        ),
        migrations.AddField(
            model_name='account',
            name='group_name',
            field=models.BooleanField(default=False, verbose_name='Обращение к пользователю в беседах'),
        ),
        migrations.AddField(
            model_name='account',
            name='ls_user',
            field=models.BooleanField(default=True, verbose_name='Обращение в личных сообщениях'),
        ),
        migrations.AddField(
            model_name='account',
            name='mark',
            field=models.CharField(default='bot', max_length=15, verbose_name='Метка бота'),
        ),
        migrations.AddField(
            model_name='account',
            name='reply',
            field=models.BooleanField(default=True, verbose_name='Пересылать сообщения собеседника в беседах'),
        ),
        migrations.AddField(
            model_name='account',
            name='sleep',
            field=models.PositiveIntegerField(default=0, verbose_name='Задержка перед отправкой сообщения'),
        ),
        migrations.AddField(
            model_name='account',
            name='voice_bot',
            field=models.BooleanField(default=False, verbose_name='Ответ голосовыми сообщениями'),
        ),
        migrations.AlterField(
            model_name='account',
            name='call',
            field=models.CharField(max_length=30, verbose_name='Имя бота'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='Бот', max_length=15, verbose_name='Обращение бота'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.TextField(default='vk.com/roofchick', verbose_name='Статус'),
        ),
    ]
