# Generated by Django 3.2 on 2021-06-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210605_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(max_length=100, verbose_name='Токен бота'),
        ),
    ]
